"""Report Generator - Composes MLE report from layer-generated sections."""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

from core.state import StateContext
from core.llm import LLMClient


class ReportGenerator:
    """
    Generates MLE report by composing LLM-generated layer sections.

    The report is assembled from:
    - A header with dataset metadata
    - A task understanding section (LLM-generated)
    - Individual layer report sections (L0-L3)

    After assembly, three LLM review passes refine the report:
    1. Strict reviewer: check contradictions and logical inconsistencies
    2. ML researcher: propose cutting-edge suggestions
    3. Final revision: incorporate reviews without discarding valid analysis
    """

    def __init__(self, llm: Optional[LLMClient] = None):
        self.llm = llm

    def generate(
        self,
        state: StateContext,
        task_config: Dict[str, Any],
        output_path: Path
    ) -> str:
        """
        Generate the MLE report.

        Args:
            state: Final pipeline state with all insights.
            task_config: Task configuration.
            output_path: Path to save the report.

        Returns:
            Path to the generated report.
        """
        print("[REPORT] Generating MLE report...")

        sections = []

        # 1. Report header
        sections.append(self._build_header(state, task_config))

        # 2. Task understanding (LLM-generated from description + data)
        task_understanding = self._generate_task_understanding(state, task_config)
        sections.append("## Task Understanding\n")
        sections.append(task_understanding)
        sections.append("\n---\n")

        # 3. Layer report sections
        for layer, heading in [
            ("L0", "1. Data Quality Analysis (L0)"),
            ("L1", "2. Unsupervised Exploration (L1)"),
            ("L2", "3. Task-Aligned Feature Analysis (L2)"),
            ("L3", "4. Modeling Strategy (L3)"),
        ]:
            section_md = state.layer_reports.get(layer, "")
            sections.append(f"## {heading}\n")
            if section_md:
                sections.append(section_md)
            else:
                status = state.layer_status.get(layer, "unknown")
                sections.append(
                    f"*{layer} report section not available (layer status: {status}).*"
                )
            sections.append("\n---\n")

        sections.append("*Report generated by Data Profiler*\n")

        draft_report = "\n".join(sections)

        # 4. Three-pass LLM review
        final_report = self._review_and_revise(draft_report, state, task_config)

        # Save report
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(final_report)

        print(f"[REPORT] Report saved to: {output_path}")
        return str(output_path)

    def _build_header(
        self,
        state: StateContext,
        task_config: Dict[str, Any],
    ) -> str:
        """Build report header with dataset metadata."""
        dataset = task_config.get("dataset", "Unknown")
        total_rows = state.l0_stats.get("total_rows", "N/A")
        total_cols = state.l0_stats.get("total_columns", "N/A")

        return f"""# MLE Data Profiling Report

**Dataset:** {dataset}
**Rows:** {total_rows}
**Columns:** {total_cols}

---
"""

    def _generate_task_understanding(
        self,
        state: StateContext,
        task_config: Dict[str, Any],
    ) -> str:
        """Generate a concise task understanding section from description + data."""
        if not self.llm:
            return self._fallback_task_understanding(task_config)

        description = task_config.get("description", "")
        file_inventory = task_config.get("_file_inventory", "")

        prompt = f"""Based on the task description and data below, write a concise task understanding section (3-5 sentences).

Cover:
1. What the dataset is about (domain, source)
2. What the prediction task is (target variable, task type, metric)
3. Key characteristics of the data (size, main feature types)
4. Any important constraints or challenges mentioned in the description

Task description:
{description[:2000]}

Data overview:
- Dataset: {task_config.get('dataset', 'Unknown')}
- Target: {task_config.get('target', 'N/A')}
- Task type: {task_config.get('task_type', 'N/A')}
- Metric: {task_config.get('metric', 'N/A')}
- Rows: {state.l0_stats.get('total_rows', 'N/A')}
- Columns: {state.l0_stats.get('total_columns', 'N/A')}

{f"File inventory:{chr(10)}{file_inventory[:1000]}" if file_inventory else ""}

Be factual and concise. Do not use markdown headers — just paragraphs."""

        result = self.llm.generate(
            system_prompt="You are a data scientist writing a brief task overview.",
            user_prompt=prompt,
        )

        if result["success"]:
            return result["content"]
        return self._fallback_task_understanding(task_config)

    def _fallback_task_understanding(self, task_config: Dict[str, Any]) -> str:
        """Simple fallback when LLM is unavailable."""
        target = task_config.get("target", "N/A")
        task_type = task_config.get("task_type", "N/A")
        desc = task_config.get("description", "")
        summary = desc[:200].strip() if desc else "No description provided."
        return (
            f"**Task:** Predict `{target}` ({task_type}). "
            f"{summary}"
        )

    def _review_and_revise(
        self,
        draft_report: str,
        state: StateContext,
        task_config: Dict[str, Any],
    ) -> str:
        """
        Three-pass LLM review:
        1. Strict reviewer: find contradictions, logical gaps
        2. ML researcher: propose cutting-edge suggestions
        3. Final revision: incorporate feedback without discarding valid analysis
        """
        if not self.llm:
            return draft_report

        # --- Pass 1: Strict reviewer ---
        print("[REPORT] Review pass 1/3: strict consistency check...")
        review_1 = self._llm_review(
            draft_report,
            system_prompt=(
                "You are the most strict and rigorous technical reviewer. "
                "Your job is to find contradictions, logical inconsistencies, "
                "unsupported claims, and factual errors in data analysis reports. "
                "Be harsh but constructive."
            ),
            user_prompt=(
                "Review the following data profiling report. Identify:\n"
                "1. Any contradictions between sections (e.g., L0 says X but L2 says not-X)\n"
                "2. Logical gaps or unsupported claims\n"
                "3. Numbers or statistics that don't add up\n"
                "4. Conclusions not justified by the evidence presented\n\n"
                "For each issue found, state the problem clearly and suggest a fix.\n"
                "If the report is logically consistent, say so.\n\n"
                f"=== REPORT ===\n{draft_report[:6000]}"
            ),
        )

        # --- Pass 2: ML researcher ---
        print("[REPORT] Review pass 2/3: ML researcher suggestions...")
        review_2 = self._llm_review(
            draft_report,
            system_prompt=(
                "You are a cutting-edge ML researcher with deep expertise in "
                "modern machine learning, feature engineering, and AutoML. "
                "You stay current with the latest techniques (2024-2025)."
            ),
            user_prompt=(
                "Review the following data profiling report from a technical ML perspective. "
                "Propose concrete, actionable suggestions:\n"
                "1. Advanced feature engineering techniques that could help\n"
                "2. Modern model architectures or approaches not yet considered\n"
                "3. Better preprocessing or validation strategies\n"
                "4. Potential pitfalls in the current approach\n\n"
                "Be specific and reference the actual data/features in the report. "
                "Only suggest techniques appropriate for this dataset's scale and type.\n\n"
                f"=== REPORT ===\n{draft_report[:6000]}"
            ),
        )

        # --- Pass 3: Final revision ---
        print("[REPORT] Review pass 3/3: final revision...")
        final_report = self._llm_final_revision(
            draft_report, review_1, review_2
        )

        return final_report

    def _llm_review(
        self, report: str, system_prompt: str, user_prompt: str
    ) -> str:
        """Run a single LLM review pass and return the review text."""
        result = self.llm.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            max_tokens=2048,
        )
        if result["success"]:
            return result["content"]
        return ""

    def _llm_final_revision(
        self, draft: str, review_strict: str, review_ml: str
    ) -> str:
        """LLM produces the final revised report."""
        system_prompt = (
            "You are a senior data scientist producing the final version of a data profiling report. "
            "You have received two expert reviews. Your job is to revise the report by:\n"
            "1. Fixing any contradictions or logical issues found by the strict reviewer\n"
            "2. Incorporating valuable ML suggestions from the researcher where appropriate\n"
            "3. PRESERVING all valid, well-supported analysis from the original report\n\n"
            "Do NOT discard correct analysis just to make changes. Only modify what needs fixing "
            "or enhancing. Add new suggestions as clearly marked additions (e.g., a new subsection "
            "or appended notes), not as replacements for existing valid content.\n\n"
            "Return the complete revised report in markdown."
        )

        user_prompt = f"""=== ORIGINAL REPORT ===
{draft[:6000]}

=== STRICT REVIEWER FEEDBACK ===
{review_strict[:2000] if review_strict else "No issues found."}

=== ML RESEARCHER SUGGESTIONS ===
{review_ml[:2000] if review_ml else "No additional suggestions."}

Produce the final revised report. Keep the same overall structure.
Add a new section "## 5. Review Notes" at the end (before the footer) that summarizes:
- Issues fixed from the strict review
- ML suggestions incorporated or noted for future work"""

        result = self.llm.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            max_tokens=8192,
        )

        if result["success"]:
            return result["content"]
        # If revision fails, return draft with reviews appended
        fallback_parts = [draft.rstrip()]
        if review_strict:
            fallback_parts.append("\n---\n\n## 5. Review Notes\n")
            fallback_parts.append("### Strict Review\n")
            fallback_parts.append(review_strict)
        if review_ml:
            fallback_parts.append("\n### ML Researcher Suggestions\n")
            fallback_parts.append(review_ml)
        return "\n".join(fallback_parts)

    @staticmethod
    def _to_rate(value: Any) -> float:
        """Normalize percentage/proportion values into [0, 1] proportion."""
        try:
            val = float(value)
        except (TypeError, ValueError):
            return 0.0
        if val > 1:
            return val / 100.0
        return val


def generate_layer_diagnostics(state: StateContext, output_path: Path) -> str:
    """Generate a concise markdown diagnostics file for multi-turn execution."""
    lines = [
        "# Layer Diagnostics",
        "",
        "## Status",
    ]

    if state.layer_status:
        lines.append("| Layer | Status | Turns |")
        lines.append("|-------|--------|-------|")
        for layer in ["L0", "L1", "L2", "L3"]:
            lines.append(
                f"| {layer} | {state.layer_status.get(layer, 'unknown')} | "
                f"{len(state.layer_runs.get(layer, []))} |"
            )
    else:
        lines.append("No layer status recorded.")

    lines.append("")
    lines.append("## Decisions")
    if state.agent_decisions:
        for layer in ["L0", "L1", "L2", "L3"]:
            decisions = state.agent_decisions.get(layer, [])
            if not decisions:
                continue
            lines.append(f"### {layer}")
            for item in decisions:
                lines.append(
                    f"- Turn {item.get('turn', '?')}: {item.get('plan', '')} "
                    f"(prev_best={item.get('previous_best_score', 0)})"
                )
            lines.append("")
    else:
        lines.append("No decisions recorded.")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).strip() + "\n")

    print(f"[REPORT] Layer diagnostics saved to: {output_path}")
    return str(output_path)


def generate_preprocessing_script(state: StateContext, output_path: Path) -> str:
    """
    Generate a standalone preprocessing script from the pipeline state.

    Args:
        state: Final pipeline state.
        output_path: Path to save the script.

    Returns:
        Path to the generated script.
    """
    script_parts = [
        '"""Auto-generated preprocessing pipeline from Data Profiler."""',
        "",
        "import pandas as pd",
        "import numpy as np",
        "from sklearn.preprocessing import LabelEncoder",
        "",
        "",
        "def preprocess(df: pd.DataFrame) -> pd.DataFrame:",
        '    """Apply preprocessing transformations to the dataframe."""',
        "    df = df.copy()",
        ""
    ]

    # Add cleaning actions
    for action in state.l0_cleaning_actions:
        if action["action"] == "drop_column":
            script_parts.append(f'    # Drop: {action["reason"]}')
            script_parts.append(f'    if "{action["target"]}" in df.columns:')
            script_parts.append(f'        df = df.drop(columns=["{action["target"]}"])')
            script_parts.append("")

    # Add transformations
    for transform in state.l2_transformations:
        feat = transform.get("feature", "")
        trans_type = transform.get("transform", "")

        if trans_type == "log":
            script_parts.append(f'    # Log transform: {transform.get("reason", "")}')
            script_parts.append(f'    if "{feat}" in df.columns:')
            script_parts.append(f'        min_val = df["{feat}"].min()')
            script_parts.append(f'        if min_val <= 0:')
            script_parts.append(f'            df["{feat}_log"] = np.log1p(df["{feat}"] - min_val + 1)')
            script_parts.append(f'        else:')
            script_parts.append(f'            df["{feat}_log"] = np.log1p(df["{feat}"])')
            script_parts.append("")

        elif trans_type == "sqrt":
            script_parts.append(f'    # Sqrt transform: {transform.get("reason", "")}')
            script_parts.append(f'    if "{feat}" in df.columns:')
            script_parts.append(f'        df["{feat}_sqrt"] = np.sqrt(np.abs(df["{feat}"]))')
            script_parts.append("")

    script_parts.append("    return df")
    script_parts.append("")
    script_parts.append("")
    script_parts.append('if __name__ == "__main__":')
    script_parts.append('    import sys')
    script_parts.append('    if len(sys.argv) < 2:')
    script_parts.append('        print("Usage: python preprocess_pipeline.py <input.csv> [output.csv]")')
    script_parts.append('        sys.exit(1)')
    script_parts.append('    ')
    script_parts.append('    input_path = sys.argv[1]')
    script_parts.append('    output_path = sys.argv[2] if len(sys.argv) > 2 else "preprocessed.csv"')
    script_parts.append('    ')
    script_parts.append('    df = pd.read_csv(input_path)')
    script_parts.append('    df_processed = preprocess(df)')
    script_parts.append('    df_processed.to_csv(output_path, index=False)')
    script_parts.append('    print(f"Preprocessed data saved to {output_path}")')

    script_content = "\n".join(script_parts)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(script_content)

    print(f"[REPORT] Preprocessing script saved to: {output_path}")
    return str(output_path)


def generate_execution_trace(state: StateContext, output_path: Path) -> str:
    """
    Generate a human-readable execution trace with code, stdout, and LLM I/O.

    Shows per-layer, per-turn details of what code was executed, what the LLM
    generated, and how the agent converged.
    """
    lines = [
        "# Execution Trace",
        "",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]

    layer_names = {
        "L0": "Data Quality Analysis",
        "L1": "Unsupervised Exploration",
        "L2": "Task-Aligned Feature Validation",
        "L3": "AutoML Strategy",
    }

    for layer in ["L0", "L1", "L2", "L3"]:
        turns = state.layer_runs.get(layer, [])
        if not turns:
            continue

        status = state.layer_status.get(layer, "unknown")
        title = layer_names.get(layer, layer)
        lines.append(f"## {layer} — {title} (status: {status})")
        lines.append("")

        for turn_record in turns:
            turn_num = turn_record.get("turn", "?")
            score = turn_record.get("score", "N/A")
            decision = turn_record.get("decision", "N/A")
            success = turn_record.get("success", False)

            lines.append(f"### Turn {turn_num} — score={score}, decision={decision}, success={success}")
            lines.append("")

            # Code snippets
            snippets = turn_record.get("code_snippets", [])
            if snippets:
                lines.append("#### Code Executed")
                lines.append("")
                for i, snippet in enumerate(snippets, 1):
                    desc = snippet.get("description", f"Snippet {i}")
                    snip_success = snippet.get("success", "N/A")
                    lines.append(f"**{i}. {desc}** (success={snip_success})")
                    lines.append("")
                    code = snippet.get("code", "")
                    if code:
                        lines.append("```python")
                        lines.append(code[:4000])
                        lines.append("```")
                        lines.append("")
                    stdout = snippet.get("stdout", "")
                    if stdout:
                        lines.append("**stdout:**")
                        lines.append("```")
                        lines.append(stdout[:3000])
                        lines.append("```")
                        lines.append("")

            # LLM interactions
            interactions = turn_record.get("llm_interactions", [])
            if interactions:
                lines.append("#### LLM Interactions")
                lines.append("")
                for interaction in interactions:
                    role = interaction.get("role", "unknown")
                    int_success = interaction.get("success", "N/A")
                    lines.append(f"**{role}** (success={int_success})")
                    lines.append("")
                    prompt = interaction.get("user_prompt", "")
                    if prompt:
                        lines.append("<details><summary>User Prompt</summary>")
                        lines.append("")
                        lines.append("```")
                        lines.append(prompt[:3000])
                        lines.append("```")
                        lines.append("")
                        lines.append("</details>")
                        lines.append("")
                    response = interaction.get("raw_response", "")
                    if response:
                        lines.append("<details><summary>LLM Response</summary>")
                        lines.append("")
                        lines.append("```")
                        lines.append(response[:3000])
                        lines.append("```")
                        lines.append("")
                        lines.append("</details>")
                        lines.append("")

            # Observation and error
            obs = turn_record.get("observation", "")
            if obs:
                lines.append(f"**Observation:** {obs}")
                lines.append("")
            err = turn_record.get("error")
            if err:
                lines.append(f"**Error:** {err}")
                lines.append("")

            lines.append("---")
            lines.append("")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).strip() + "\n")

    print(f"[REPORT] Execution trace saved to: {output_path}")
    return str(output_path)
